title: 首页
description: 极限编程训练营
keywords: eXtreme Programming, XP
baseurl: ""
permalink: /:title/
url: https://xpbootcamp.cn
img_path: /assets/images
image_path_post: /assets/images/post

author:
  name: 袁慎建
  first_name: Shenjian
  last_name: Yuan
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: yuanshenjian
  facebook_username:
  twitter_username:
  jianshu: https://www.jianshu.com/u/c379cdabd121/
  email: sjyuan@thoughtworks.com
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now

encoding: utf-8

# other settings
#highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: assets/_sass
  style: compressed

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

gitalk:
  clientID: 'efef4d3fd85669ad05a9'
  clientSecret: '64fa1ed9e53a5f2d077be36b88f02fe2212a9c2a'
  repo: 'xp-bootcamp.github.io'
  owner: 'xp-bootcamp'
  admin: ['xp-bootcamp']
